global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    retention_policy: "7d"

scrape_configs:
  - job_name: app
    metrics_path: /metrics
    static_configs:
      - targets: ['app:8000']
