apiVersion: v1
kind: Service
metadata:
  name: model-serving
  labels:
    app.kubernetes.io/name: model-serving
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: model-serving
  ports:
    - name: http
      port: 8000
      targetPort: 8000
