apiVersion: v2
name: basic-model-serving
description: Model-serving API for minikube deployment via werf
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: kube-prometheus-stack
    version: "~87.12.0"
    repository: https://prometheus-community.github.io/helm-charts
